site_name: FastHTML Dashboard Tutorial
site_url: https://mydomain.org/mysite
repo_url: https://github.com/pydanny/fasthtml-dashboard
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details  